-- ════════════════════════════════════════════════════════════════════════
-- scrape_config — Część 2: 14 nisz × rynki (PL/US/UK/DE/FR/ES), produktowe +
-- kategorialne frazy (łapanie świeżych produktów). rotation_group: 0=codziennie
-- (PL), 1=parzysty dzień (US,DE,ES), 2=nieparzysty (UK,FR). Idempotentny.
-- Wygenerowane przez scripts (źródło: scrape_config_geo gen). 211 wierszy.
-- ════════════════════════════════════════════════════════════════════════
insert into scrape_config (source, query, country, niche, rotation_group, is_active, max_results)
select v.source, v.query, v.country, v.niche::niche_type, v.rg, true, v.mr
from (values
  ('meta_ad_library','gua sha','PL','beauty',0,20),
  ('meta_ad_library','serum do twarzy','PL','beauty',0,20),
  ('meta_ad_library','krem przeciwzmarszczkowy','PL','beauty',0,20),
  ('meta_ad_library','peeling','PL','beauty',0,20),
  ('meta_ad_library','akcesoria do pielęgnacji twarzy','PL','beauty',0,20),
  ('meta_ad_library','gadżet kosmetyczny','PL','beauty',0,20),
  ('meta_ad_library','korektor postawy','PL','fitness',0,20),
  ('meta_ad_library','taśmy oporowe','PL','fitness',0,20),
  ('meta_ad_library','masażer','PL','fitness',0,20),
  ('meta_ad_library','akcesoria fitness','PL','fitness',0,20),
  ('meta_ad_library','sprzęt do ćwiczeń w domu','PL','fitness',0,20),
  ('meta_ad_library','projektor gwiazd','PL','home',0,20),
  ('meta_ad_library','organizer','PL','home',0,20),
  ('meta_ad_library','lampka led','PL','home',0,20),
  ('meta_ad_library','wkrętarka akumulatorowa','PL','home',0,20),
  ('meta_ad_library','gadżet do domu','PL','home',0,20),
  ('meta_ad_library','akcesoria do salonu','PL','home',0,20),
  ('meta_ad_library','narzędzia do domu','PL','home',0,20),
  ('meta_ad_library','blender ręczny','PL','kitchen',0,20),
  ('meta_ad_library','patelnia granitowa','PL','kitchen',0,20),
  ('meta_ad_library','krajalnica','PL','kitchen',0,20),
  ('meta_ad_library','gadżet kuchenny','PL','kitchen',0,20),
  ('meta_ad_library','akcesoria do kuchni','PL','kitchen',0,20),
  ('meta_ad_library','szelki dla psa','PL','pet',0,20),
  ('meta_ad_library','lokalizator gps pies','PL','pet',0,20),
  ('meta_ad_library','drapak','PL','pet',0,20),
  ('meta_ad_library','akcesoria dla psa','PL','pet',0,20),
  ('meta_ad_library','gadżet dla kota','PL','pet',0,20),
  ('meta_ad_library','powerbank','PL','gadgets',0,20),
  ('meta_ad_library','lokalizator kluczy','PL','gadgets',0,20),
  ('meta_ad_library','etui magsafe','PL','gadgets',0,20),
  ('meta_ad_library','lampa ring','PL','gadgets',0,20),
  ('meta_ad_library','gadżet elektroniczny','PL','gadgets',0,20),
  ('meta_ad_library','nietypowy gadżet','PL','gadgets',0,20),
  ('meta_ad_library','akcesoria do telefonu','PL','gadgets',0,20),
  ('meta_ad_library','portfel slim','PL','fashion',0,20),
  ('meta_ad_library','zegarek smart','PL','fashion',0,20),
  ('meta_ad_library','okulary fotochromowe','PL','fashion',0,20),
  ('meta_ad_library','modne akcesoria','PL','fashion',0,20),
  ('meta_ad_library','gadżet do ubrań','PL','fashion',0,20),
  ('meta_ad_library','nosidełko','PL','baby',0,20),
  ('meta_ad_library','mata edukacyjna','PL','baby',0,20),
  ('meta_ad_library','butelka antykolkowa','PL','baby',0,20),
  ('meta_ad_library','akcesoria dla niemowląt','PL','baby',0,20),
  ('meta_ad_library','gadżet dla dziecka','PL','baby',0,20),
  ('meta_ad_library','kamera samochodowa','PL','auto',0,20),
  ('meta_ad_library','odkurzacz samochodowy','PL','auto',0,20),
  ('meta_ad_library','organizer do bagażnika','PL','auto',0,20),
  ('meta_ad_library','akcesoria samochodowe','PL','auto',0,20),
  ('meta_ad_library','gadżet do auta','PL','auto',0,20),
  ('meta_ad_library','lampy solarne','PL','garden',0,20),
  ('meta_ad_library','wąż ogrodowy rozciągliwy','PL','garden',0,20),
  ('meta_ad_library','donica samonawadniająca','PL','garden',0,20),
  ('meta_ad_library','akcesoria ogrodowe','PL','garden',0,20),
  ('meta_ad_library','gadżet do ogrodu','PL','garden',0,20),
  ('meta_ad_library','robot sprzątający','PL','tech',0,20),
  ('meta_ad_library','nawilżacz powietrza','PL','tech',0,20),
  ('meta_ad_library','oczyszczacz powietrza','PL','tech',0,20),
  ('meta_ad_library','nowoczesne agd','PL','tech',0,20),
  ('meta_ad_library','gadżet do domu smart','PL','tech',0,20),
  ('meta_ad_library','organizer na biurko','PL','office',0,20),
  ('meta_ad_library','lampka biurkowa','PL','office',0,20),
  ('meta_ad_library','podstawka pod laptopa','PL','office',0,20),
  ('meta_ad_library','akcesoria na biurko','PL','office',0,20),
  ('meta_ad_library','gadżet do biura','PL','office',0,20),
  ('meta_ad_library','gua sha','US','beauty',1,20),
  ('meta_ad_library','gua sha','UK','beauty',2,20),
  ('meta_ad_library','ice roller','US','beauty',1,20),
  ('meta_ad_library','ice roller','UK','beauty',2,20),
  ('meta_ad_library','blackhead remover vacuum','US','beauty',1,20),
  ('meta_ad_library','blackhead remover vacuum','UK','beauty',2,20),
  ('meta_ad_library','vitamin c serum','US','beauty',1,20),
  ('meta_ad_library','vitamin c serum','UK','beauty',2,20),
  ('meta_ad_library','skincare gadget','US','beauty',1,20),
  ('meta_ad_library','skincare gadget','UK','beauty',2,20),
  ('meta_ad_library','face care tool','US','beauty',1,20),
  ('meta_ad_library','face care tool','UK','beauty',2,20),
  ('meta_ad_library','posture corrector','US','fitness',1,20),
  ('meta_ad_library','posture corrector','UK','fitness',2,20),
  ('meta_ad_library','resistance bands','US','fitness',1,20),
  ('meta_ad_library','resistance bands','UK','fitness',2,20),
  ('meta_ad_library','massage gun','US','fitness',1,20),
  ('meta_ad_library','massage gun','UK','fitness',2,20),
  ('meta_ad_library','fitness gadget','US','fitness',1,20),
  ('meta_ad_library','fitness gadget','UK','fitness',2,20),
  ('meta_ad_library','home workout gear','US','fitness',1,20),
  ('meta_ad_library','home workout gear','UK','fitness',2,20),
  ('meta_ad_library','galaxy projector','US','home',1,20),
  ('meta_ad_library','galaxy projector','UK','home',2,20),
  ('meta_ad_library','led strip lights','US','home',1,20),
  ('meta_ad_library','led strip lights','UK','home',2,20),
  ('meta_ad_library','cordless drill','US','home',1,20),
  ('meta_ad_library','cordless drill','UK','home',2,20),
  ('meta_ad_library','home gadget','US','home',1,20),
  ('meta_ad_library','home gadget','UK','home',2,20),
  ('meta_ad_library','cool home accessory','US','home',1,20),
  ('meta_ad_library','cool home accessory','UK','home',2,20),
  ('meta_ad_library','vegetable chopper','US','kitchen',1,20),
  ('meta_ad_library','vegetable chopper','UK','kitchen',2,20),
  ('meta_ad_library','electric spin scrubber','US','kitchen',1,20),
  ('meta_ad_library','electric spin scrubber','UK','kitchen',2,20),
  ('meta_ad_library','portable blender','US','kitchen',1,20),
  ('meta_ad_library','portable blender','UK','kitchen',2,20),
  ('meta_ad_library','kitchen gadget','US','kitchen',1,20),
  ('meta_ad_library','kitchen gadget','UK','kitchen',2,20),
  ('meta_ad_library','kitchen accessory','US','kitchen',1,20),
  ('meta_ad_library','kitchen accessory','UK','kitchen',2,20),
  ('meta_ad_library','dog gps tracker','US','pet',1,20),
  ('meta_ad_library','dog gps tracker','UK','pet',2,20),
  ('meta_ad_library','slow feeder bowl','US','pet',1,20),
  ('meta_ad_library','slow feeder bowl','UK','pet',2,20),
  ('meta_ad_library','cat water fountain','US','pet',1,20),
  ('meta_ad_library','cat water fountain','UK','pet',2,20),
  ('meta_ad_library','dog accessory','US','pet',1,20),
  ('meta_ad_library','dog accessory','UK','pet',2,20),
  ('meta_ad_library','cat gadget','US','pet',1,20),
  ('meta_ad_library','cat gadget','UK','pet',2,20),
  ('meta_ad_library','bluetooth tracker','US','gadgets',1,20),
  ('meta_ad_library','bluetooth tracker','UK','gadgets',2,20),
  ('meta_ad_library','magsafe case','US','gadgets',1,20),
  ('meta_ad_library','magsafe case','UK','gadgets',2,20),
  ('meta_ad_library','ring light','US','gadgets',1,20),
  ('meta_ad_library','ring light','UK','gadgets',2,20),
  ('meta_ad_library','cool gadget','US','gadgets',1,20),
  ('meta_ad_library','cool gadget','UK','gadgets',2,20),
  ('meta_ad_library','phone accessory','US','gadgets',1,20),
  ('meta_ad_library','phone accessory','UK','gadgets',2,20),
  ('meta_ad_library','minimalist wallet','US','fashion',1,20),
  ('meta_ad_library','minimalist wallet','UK','fashion',2,20),
  ('meta_ad_library','smart watch','US','fashion',1,20),
  ('meta_ad_library','smart watch','UK','fashion',2,20),
  ('meta_ad_library','blue light glasses','US','fashion',1,20),
  ('meta_ad_library','blue light glasses','UK','fashion',2,20),
  ('meta_ad_library','trendy accessory','US','fashion',1,20),
  ('meta_ad_library','trendy accessory','UK','fashion',2,20),
  ('meta_ad_library','fashion gadget','US','fashion',1,20),
  ('meta_ad_library','fashion gadget','UK','fashion',2,20),
  ('meta_ad_library','baby carrier','US','baby',1,20),
  ('meta_ad_library','baby carrier','UK','baby',2,20),
  ('meta_ad_library','white noise machine','US','baby',1,20),
  ('meta_ad_library','white noise machine','UK','baby',2,20),
  ('meta_ad_library','silicone bib','US','baby',1,20),
  ('meta_ad_library','silicone bib','UK','baby',2,20),
  ('meta_ad_library','baby accessory','US','baby',1,20),
  ('meta_ad_library','baby accessory','UK','baby',2,20),
  ('meta_ad_library','baby gadget','US','baby',1,20),
  ('meta_ad_library','baby gadget','UK','baby',2,20),
  ('meta_ad_library','car vacuum cleaner','US','auto',1,20),
  ('meta_ad_library','car vacuum cleaner','UK','auto',2,20),
  ('meta_ad_library','dash cam','US','auto',1,20),
  ('meta_ad_library','dash cam','UK','auto',2,20),
  ('meta_ad_library','car trunk organizer','US','auto',1,20),
  ('meta_ad_library','car trunk organizer','UK','auto',2,20),
  ('meta_ad_library','car accessory','US','auto',1,20),
  ('meta_ad_library','car accessory','UK','auto',2,20),
  ('meta_ad_library','car gadget','US','auto',1,20),
  ('meta_ad_library','car gadget','UK','auto',2,20),
  ('meta_ad_library','solar garden lights','US','garden',1,20),
  ('meta_ad_library','solar garden lights','UK','garden',2,20),
  ('meta_ad_library','expandable hose','US','garden',1,20),
  ('meta_ad_library','expandable hose','UK','garden',2,20),
  ('meta_ad_library','self-watering planter','US','garden',1,20),
  ('meta_ad_library','self-watering planter','UK','garden',2,20),
  ('meta_ad_library','garden accessory','US','garden',1,20),
  ('meta_ad_library','garden accessory','UK','garden',2,20),
  ('meta_ad_library','garden gadget','US','garden',1,20),
  ('meta_ad_library','garden gadget','UK','garden',2,20),
  ('meta_ad_library','robot vacuum','US','tech',1,20),
  ('meta_ad_library','robot vacuum','UK','tech',2,20),
  ('meta_ad_library','air purifier','US','tech',1,20),
  ('meta_ad_library','air purifier','UK','tech',2,20),
  ('meta_ad_library','wireless earbuds','US','tech',1,20),
  ('meta_ad_library','wireless earbuds','UK','tech',2,20),
  ('meta_ad_library','smart home gadget','US','tech',1,20),
  ('meta_ad_library','smart home gadget','UK','tech',2,20),
  ('meta_ad_library','home appliance','US','tech',1,20),
  ('meta_ad_library','home appliance','UK','tech',2,20),
  ('meta_ad_library','laptop stand','US','office',1,20),
  ('meta_ad_library','laptop stand','UK','office',2,20),
  ('meta_ad_library','led desk lamp','US','office',1,20),
  ('meta_ad_library','led desk lamp','UK','office',2,20),
  ('meta_ad_library','desk organizer','US','office',1,20),
  ('meta_ad_library','desk organizer','UK','office',2,20),
  ('meta_ad_library','desk accessory','US','office',1,20),
  ('meta_ad_library','desk accessory','UK','office',2,20),
  ('meta_ad_library','office gadget','US','office',1,20),
  ('meta_ad_library','office gadget','UK','office',2,20),
  ('meta_ad_library','haltungskorrektur','DE','fitness',1,20),
  ('meta_ad_library','auto staubsauger','DE','auto',1,20),
  ('meta_ad_library','saugroboter','DE','tech',1,20),
  ('meta_ad_library','nackenmassagegerät','DE','tech',1,20),
  ('meta_ad_library','led streifen','DE','home',1,20),
  ('meta_ad_library','hundegeschirr','DE','pet',1,20),
  ('meta_ad_library','solarleuchten garten','DE','garden',1,20),
  ('meta_ad_library','gua sha','DE','beauty',1,20),
  ('meta_ad_library','correcteur de posture','FR','fitness',2,20),
  ('meta_ad_library','aspirateur voiture sans fil','FR','auto',2,20),
  ('meta_ad_library','aspirateur robot','FR','tech',2,20),
  ('meta_ad_library','appareil massage nuque','FR','tech',2,20),
  ('meta_ad_library','ruban led','FR','home',2,20),
  ('meta_ad_library','harnais chien','FR','pet',2,20),
  ('meta_ad_library','lampe solaire jardin','FR','garden',2,20),
  ('meta_ad_library','gua sha','FR','beauty',2,20),
  ('meta_ad_library','corrector de postura','ES','fitness',1,20),
  ('meta_ad_library','aspirador de coche','ES','auto',1,20),
  ('meta_ad_library','robot aspirador','ES','tech',1,20),
  ('meta_ad_library','masajeador de cuello','ES','tech',1,20),
  ('meta_ad_library','tira led','ES','home',1,20),
  ('meta_ad_library','arnés perro','ES','pet',1,20),
  ('meta_ad_library','luces solares jardín','ES','garden',1,20),
  ('meta_ad_library','gua sha','ES','beauty',1,20)
) as v(source, query, country, niche, rg, mr)
where not exists (
  select 1 from scrape_config sc where sc.source=v.source and sc.query=v.query and sc.country=v.country
);

-- ustaw rotation_group na istniejących PL (FAZA B) → 0 (codziennie)
update scrape_config set rotation_group = 0 where country = 'PL' and rotation_group is distinct from 0;
